server:
  port: 3002

spring:
  application:
    name: data-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/b033521b-5a18-4110-9d4e-9f28f461e099/

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG